version: "3"

services:
  database:
    container_name: mariadb
    image: mariadb:jammy
    ports:
      - 3306:3306
    volumes:
      - BdPostgres-Mio:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345

  phpmyadmin:
    depends_on:
      - database
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    volumes:
      - ./phpmyadmin:/var/www/html
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306

volumes:
  BdPostgres-Mio:
